import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Navbar from "../components/NavBar";
import './globals.css';
export const metadata = {
  title: "DNYX Blogs | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col bg-gray-100 dark:bg-gray-950 text-black dark:text-white p-2">
        <Header />
        <Navbar />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
